version: '3'
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    shm_size: '2g'

  selenium-test:
    image: python:3.12
    container_name: selenium-test-container
    volumes:
      - .:/test_codigo
    working_dir: /test_codigo
    depends_on:
      - selenium-chrome
    command:
      - bash
      - -c
      - |
        pip install -r requirements.txt && python -m unittest discover
